variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_app_subnet_az1_cidr" {}
variable "private_app_subnet_az2_cidr" {}
variable "private_data_subnet_az1_cidr" {}
variable "private_data_subnet_az2_cidr" {}
variable "ami_id" {}
variable "instance_type" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "launch_template_id" {}

variable "health_check_type" {}
variable "health_check_grace_period" {}
variable "key_name" {}
variable "volume_size" {}
variable "volume_type" {}
variable "bastion_ami_id" {}
variable "bastion_instance_type" {}
variable "db_username" {}
variable "db_password" {}
variable "app_sg_id" {}
variable "db_engine_version" {}
variable "db_instance_class" {}
variable "db_allocated_storage" {}
